ALL: ej-1 ej-2 ej-3
.PHONY= clean

clean:
	\rm -rf ej-* datos

ej-1: ejercicio1.c
	gcc -g ejercicio1.c -o ej-1

ej-2: ejercicio2.c
	gcc -g ejercicio2.c -o ej-2

ej-3: ejercicio3.c
	gcc -g ejercicio3.c -o ej-3
