ALL: ej-1 ej-2 ej-3 ej-4
.PHONY=clean

ej-1:ejercicio1.c
	gcc -g ejercicio1.c -o ej-1 -lpthread

ej-2:ejercicio2.c
	gcc -g ejercicio2.c -o ej-2 -lpthread

ej-3:ejercicio3.c
	gcc -g ejercicio3.c -o ej-3 -lpthread

ej-4:ejercicio4.c
	gcc -g ejercicio4.c -o ej-4 -lpthread

clean:
	\rm -f ej-*
