All: ej-2 ej-3 ej-4R ej-4W

.PHONY=clean

clean:
	\rm -f ej-*

ej-2: ejercicio2.c
	gcc ejercicio2.c -g -o ej-2

ej-3: ejercicio3.c
	gcc ejercicio3.c -g -o ej-3

ej-4R: factorial_fifo_read.c
	gcc factorial_fifo_read.c -g -o ej-4R

ej-4W: factorial_fifo_write.c
	gcc factorial_fifo_write.c -g -o ej-4W
