ALL: ej-1 ej-2 ej-3 ej-4 ej-5

.PHONY=clean

ej-1: ejercicio1.c
	gcc ejercicio1.c -g -o ej-1

ej-2: ejercicio2.c
	gcc ejercicio2.c -g -o ej-2 

ej-3: ejercicio3.c
	gcc ejercicio3.c -g -o ej-3

ej-4: ejercicio4.c
	gcc ejercicio4.c -g -o ej-4

ej-5: ejercicio5.c
	gcc ejercicio5.c -g -o ej-5

clean:
	\rm -r ej-*

