ALL: ej-1 ej-2 ej-3

.PHONY=clean

ej-1: ejercicio1.c
	gcc ejercicio1.c -g -o ej-1

ej-2: ejercicio2.c
	gcc ejercicio2.c -g -o ej-2 

ej-3: ejercicio3.c
	gcc ejercicio3.c -g -o ej-3

clean:
	\rm -r ej-*

